### ISSUE TITLE
Can I add spliced or unspliced info to my SeuratObject?

### ISSUE THREAD

**Issue by AAA-3** [satijalab/seurat-wrappers#111]
Hello every one!

I have 10X Genomics output from multiple runs. From each run, I created a Seurat Object from the `output/filtered_gene_bc_matrices/`  folders and then merged them into 1 seurat object.

I used the above merged object for all my clustering analysis and have exported this all as an RDS file.

I want to know how I can include spliced and unspliced mRNA data into the Seurat object so that I can do some scVelo RNA velocity analysis. Any thoughts?

[This vignette ](http://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/scvelo.html)seems to run Seurat analysis from a loom file that already has splicing info - how do I go the other way around?

**Comment by samuel-marsh** [comment]
Hi @AAA-3,

You have to run Velocyto or another aligner that supports output of spliced and unspliced reads in order to do this (hence the vignette starting from a Velocyto output loom file).  10X cell ranger outputs are by default just the spliced counts (or a total or spliced and intron counts if option selected in CR5+).

Best,
Sam

**Comment by AAA-3** [comment]
Yeah I figured there would be no work around - I’m was hoping to keep my Seurat analysis because repeating it after velocyto would (maybe) change some of the output etc. since Velocyto has it’s own exclusions.  Shouldn’t be too major - thanks!!
