### ISSUE TITLE
Add tag for bioconda packaging

### ISSUE THREAD

**Issue by tdido** [satijalab/seurat-wrappers#24]
Hi. I'd like to create a bioconda package for the project, and having a version tag to be able to reference a release would be very helpful. Any chance of that?

**Comment by mojaveazure** [comment]
Hi Tomás,

Thank you for your interest in SeuratWrappers! Since this is a community-driven project, we don't have a road map in mind for the future of this package, nor do we have much say in the release schedule. Future versions of this package come at a sporadic rate, even more so than Seurat. Moreover, this package is tied to other R packages hosted on various repositories. Each of these has their own release schedule and none of them are installed when installing SeuratWrappers for the first time. A conda package doesn't make much sense as the dependency structure of this package is too varied.

Furthermore, we fully discourage the use of Conda as it tends to cause a lot of issues, especially with R packages. You can do a [quick search of "conda" on the main Seurat repo](https://github.com/satijalab/seurat/issues?utf8=%E2%9C%93&q=is%3Aissue+conda) to get an idea of why we insist that our users use R from CRAN and install our packages using `install.packages` or `remotes::install_github` (`devtools::install_github` is just a reexport of this).

If you're looking for virtual-environments for your R projects, I highly recommend checking out [`renv`](https://rstudio.github.io/renv/articles/renv.html), a virtual-environment and dependency versioneer from RStudio. Since it was built by R people for R people, our code has far fewer issues than with Conda.

**Comment by tdido** [comment]
Hi Paul.

Thank you for your detailed answer. I see your point about the dependencies. In our case, though, all our infrastructure exploits conda to take advantage of its reproducibility features, integration with snakemake, and for the fact that it being largely language-agnostic is key to complex pipelines.

In any case, we can work with a fork and packages in our own repositories. We always like to try to coordinate with the authors and contribute to the community first.

Thanks!
