### ISSUE TITLE
`as.cell_data_set()` doesn't create `reducedDims` slot any more

### ISSUE THREAD

**Issue by ahoffrichter** [satijalab/seurat-wrappers#72]
In a previous analysis with `SeuratWrappers_0.1.0` I ran `as.cell_data_set()` on my Seurat object. Later I used `names(cds_from_seurat@reducedDims)[1] <- "PCA"` to set the names of the reducedDims. 

When I run exactly the same code with the same Seurat object now with `SeuratWrappers_0.2.0` it throws an error: 

Error in names(cds_from_seurat@reducedDims)[1] <- "PCA" : 
  no slot of name "reducedDims" for this object of class "cell_data_set"

My Seurat object has 2 dimensional reductions calculated: pca, umap. 
In the documentation of the function it says that "Cell emebeddings are transferred over to the reducedDims slot." So I thought this would be done automatically, when calling the function. 

Could you let me know if there were any major changes from 0.1.0 to 0.2.0 in this function, so I can figure out what to do?

**Comment by andrewwbutler** [comment]
Hi @ahoffrichter ,

Sorry for the super late response on this. Generally, with `SingleCellExperiment` objects (of which `cell_data_set` is derived), you want to use the provided accessors/setters rather than accessing the slots directly with `@`. For example, in this case if you are trying to set the name of the first `reducedDim`, you could use 

```R
 reducedDimNames(cds)[1] <- "PCA"
```

If that doesn't work, please feel free to reopen.
